-- Create a table for Contacts
create table public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  town text,
  comments text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add a comment to the table
comment on table public.contacts is 'Table to hold contact information.';

-- Explicitly disable Row Level Security (RLS) as requested (no access control)
alter table public.contacts disable row level security;
