-- Create tags table
CREATE TABLE IF NOT EXISTS public.tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(name, user_id)
);

-- Enable RLS on tags
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own tags" ON public.tags
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own tags" ON public.tags
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own tags" ON public.tags
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own tags" ON public.tags
    FOR DELETE USING (auth.uid() = user_id);

-- Create junction table for contacts and tags
CREATE TABLE IF NOT EXISTS public.contact_tags (
    contact_id BIGINT REFERENCES public.contacts(id) ON DELETE CASCADE,
    tag_id BIGINT REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (contact_id, tag_id)
);

-- Enable RLS on contact_tags
ALTER TABLE public.contact_tags ENABLE ROW LEVEL SECURITY;

-- Policies for contact_tags need to check if the user owns the contact or tag
-- Simplified: If you can see the contact, you can see its tags.
-- Actually, RLS on junction tables can be tricky.
-- Let's just allow access if the user owns the linked contact.

CREATE POLICY "Users can view contact_tags for their contacts" ON public.contact_tags
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.contacts c 
            WHERE c.id = contact_tags.contact_id 
            AND c.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can insert contact_tags for their contacts" ON public.contact_tags
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.contacts c 
            WHERE c.id = contact_tags.contact_id 
            AND c.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can delete contact_tags for their contacts" ON public.contact_tags
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.contacts c 
            WHERE c.id = contact_tags.contact_id 
            AND c.user_id = auth.uid()
        )
    );
